/* psnotes.c generated by valac 0.14.2, the Vala compiler
 * generated from psnotes.vala, do not modify */

/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * main.c
 * Copyright (C) 2012 Zach Burnham <thejambi@gmail.com>
 * 
 * P.S.Notes is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * P.S.Notes is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>
#include <gio/gio.h>
#include <stdio.h>
#include <pango/pango.h>
#include <float.h>
#include <math.h>


#define TYPE_MAIN (main_get_type ())
#define MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_MAIN, Main))
#define MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_MAIN, MainClass))
#define IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_MAIN))
#define IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_MAIN))
#define MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_MAIN, MainClass))

typedef struct _Main Main;
typedef struct _MainClass MainClass;
typedef struct _MainPrivate MainPrivate;

#define TYPE_NOTE (note_get_type ())
#define NOTE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NOTE, Note))
#define NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_NOTE, NoteClass))
#define IS_NOTE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NOTE))
#define IS_NOTE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_NOTE))
#define NOTE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_NOTE, NoteClass))

typedef struct _Note Note;
typedef struct _NoteClass NoteClass;

#define TYPE_NOTE_EDITOR (note_editor_get_type ())
#define NOTE_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_NOTE_EDITOR, NoteEditor))
#define NOTE_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_NOTE_EDITOR, NoteEditorClass))
#define IS_NOTE_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_NOTE_EDITOR))
#define IS_NOTE_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_NOTE_EDITOR))
#define NOTE_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_NOTE_EDITOR, NoteEditorClass))

typedef struct _NoteEditor NoteEditor;
typedef struct _NoteEditorClass NoteEditorClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _Block1Data Block1Data;
#define __g_list_free__g_free0_0(var) ((var == NULL) ? NULL : (var = (_g_list_free__g_free0_ (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _pango_font_description_free0(var) ((var == NULL) ? NULL : (var = (pango_font_description_free (var), NULL)))
typedef struct _main_seldomSaveData main_seldomSaveData;
typedef struct _main_callSaveData main_callSaveData;

struct _Main {
	GtkWindow parent_instance;
	MainPrivate * priv;
};

struct _MainClass {
	GtkWindowClass parent_class;
};

struct _MainPrivate {
	Note* note;
	gint startingFontSize;
	gint fontSize;
	gchar* lastKeyName;
	gboolean needsSave;
	gboolean isOpening;
	gboolean loadingNotes;
	gboolean firstLaunch;
	GtkEntry* txtFilter;
	GtkTreeView* notesView;
	GtkTextView* noteTextView;
	NoteEditor* editor;
};

struct _Block1Data {
	int _ref_count_;
	Main * self;
	GtkTreeSelection* treeSelection;
};

struct _main_seldomSaveData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	Main* self;
	gboolean _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	gboolean _tmp5_;
	gboolean _tmp6_;
	gboolean _tmp7_;
	gboolean _tmp8_;
	gboolean _tmp9_;
};

struct _main_callSaveData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	Main* self;
	Note* _tmp0_;
	NoteEditor* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	GError* e;
	GError * _inner_error_;
};


static gpointer main_parent_class = NULL;

GType main_get_type (void) G_GNUC_CONST;
GType note_get_type (void) G_GNUC_CONST;
GType note_editor_get_type (void) G_GNUC_CONST;
#define MAIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_MAIN, MainPrivate))
enum  {
	MAIN_DUMMY_PROPERTY
};
#define MAIN_isInstalled TRUE
#define MAIN_shortcutsText "Ctrl+N: Create a new note\n" "Ctrl+O: Choose notes folder\n" "Ctrl+=: Increase font size\n" "Ctrl+-: Decrease font size\n" "Ctrl+0: Reset font size"
Main* main_new (void);
Main* main_construct (GType object_type);
gboolean zystem_get_debugOn (void);
void zystem_set_debugOn (gboolean value);
void user_data_initializeUserData (void);
static void __lambda2_ (Main* self);
static void main_createNewNote (Main* self);
static void ___lambda2__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void __lambda3_ (Main* self);
void main_changeNotesDir (Main* self);
static void ___lambda3__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void __lambda4_ (Main* self);
static void main_openNotesLocation (Main* self);
static void ___lambda4__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void __lambda5_ (Main* self);
void main_on_destroy (Main* self);
static void ___lambda5__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void __lambda6_ (Main* self);
static void main_increaseFontSize (Main* self);
static void ___lambda6__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void __lambda7_ (Main* self);
static void main_decreaseFontSize (Main* self);
static void ___lambda7__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void __lambda8_ (Main* self);
static void main_showKeyboardShortcuts (Main* self);
static void ___lambda8__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void __lambda9_ (Main* self);
static void main_menuAboutClicked (Main* self);
static void ___lambda9__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self);
static void main_setupNotesView (Main* self);
static void __lambda11_ (Main* self);
void main_onTextChanged (Main* self, GtkTextBuffer* buffer);
static void ___lambda11__gtk_text_buffer_changed (GtkTextBuffer* _sender, gpointer self);
NoteEditor* note_editor_new (GtkTextBuffer* buffer);
NoteEditor* note_editor_construct (GType object_type, GtkTextBuffer* buffer);
static void main_resetFontSize (Main* self);
static gboolean __lambda12_ (Main* self, GtkWidget* window, GdkEventKey* event);
gboolean main_onKeyPress (Main* self, GdkEventKey* key);
static gboolean ___lambda12__gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
static void __lambda13_ (Main* self);
static void ___lambda13__gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (Block1Data* _data1_);
static void main_loadNotesList (Main* self);
static void __lambda10_ (Block1Data* _data1_);
static void main_noteSelected (Main* self, GtkTreeSelection* treeSelection);
static void ___lambda10__gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self);
const gchar* user_data_get_notesDirPath (void);
static void _g_free0_ (gpointer var);
static void _g_list_free__g_free0_ (GList* self);
gchar* file_utility_getFileExtension (GFileInfo* file);
void zystem_debug (const gchar* s);
gchar* file_utility_getFileNameWithoutExtension (GFileInfo* file);
static void main_seldomSave (Main* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void main_seldomSave_finish (Main* self, GAsyncResult* _res_);
Note* note_new (const gchar* title);
Note* note_construct (GType object_type, const gchar* title);
void note_editor_startNewNote (NoteEditor* self, const gchar* text);
gchar* note_getContents (Note* self);
gchar* note_editor_getText (NoteEditor* self);
gchar* note_editor_firstLine (NoteEditor* self);
gint note_editor_lineCount (NoteEditor* self);
static gboolean main_noteTitleChanged (Main* self);
void note_rename (Note* self, const gchar* title, const gchar* text);
const gchar* note_get_title (Note* self);
static void main_changeFontSize (Main* self, gint byThisMuch);
static void main_seldomSave_data_free (gpointer _data);
static gboolean main_seldomSave_co (main_seldomSaveData* _data_);
gboolean user_data_get_seldomSave (void);
static void main_callSave (Main* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void main_callSave_finish (Main* self, GAsyncResult* _res_);
static void main_callSave_data_free (gpointer _data);
static gboolean main_callSave_co (main_callSaveData* _data_);
void note_save (Note* self, const gchar* text, GError** error);
void user_data_setNotesDir (const gchar* path);
gint main_main (gchar** args, int args_length1);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void main_finalize (GObject* obj);


/** 
 * Constructor for main P.S. Notes window.
 */
static void __lambda2_ (Main* self) {
	main_createNewNote (self);
}


static void ___lambda2__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda2_ (self);
}


static void __lambda3_ (Main* self) {
	main_changeNotesDir (self);
}


static void ___lambda3__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda3_ (self);
}


static void __lambda4_ (Main* self) {
	main_openNotesLocation (self);
}


static void ___lambda4__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda4_ (self);
}


static void __lambda5_ (Main* self) {
	main_on_destroy (self);
}


static void ___lambda5__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda5_ (self);
}


static void __lambda6_ (Main* self) {
	main_increaseFontSize (self);
}


static void ___lambda6__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda6_ (self);
}


static void __lambda7_ (Main* self) {
	main_decreaseFontSize (self);
}


static void ___lambda7__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda7_ (self);
}


static void __lambda8_ (Main* self) {
	main_showKeyboardShortcuts (self);
}


static void ___lambda8__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda8_ (self);
}


static void __lambda9_ (Main* self) {
	main_menuAboutClicked (self);
}


static void ___lambda9__gtk_menu_item_activate (GtkMenuItem* _sender, gpointer self) {
	__lambda9_ (self);
}


static void __lambda11_ (Main* self) {
	GtkTextView* _tmp0_;
	GtkTextBuffer* _tmp1_;
	GtkTextBuffer* _tmp2_;
	_tmp0_ = self->priv->noteTextView;
	_tmp1_ = gtk_text_view_get_buffer (_tmp0_);
	_tmp2_ = _tmp1_;
	main_onTextChanged (self, _tmp2_);
}


static void ___lambda11__gtk_text_buffer_changed (GtkTextBuffer* _sender, gpointer self) {
	__lambda11_ (self);
}


static gboolean __lambda12_ (Main* self, GtkWidget* window, GdkEventKey* event) {
	gboolean result = FALSE;
	GdkEventKey _tmp0_;
	gboolean _tmp1_ = FALSE;
	g_return_val_if_fail (window != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = *event;
	_tmp1_ = main_onKeyPress (self, &_tmp0_);
	result = _tmp1_;
	return result;
}


static gboolean ___lambda12__gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	gboolean result;
	result = __lambda12_ (self, _sender, event);
	return result;
}


static void __lambda13_ (Main* self) {
	main_on_destroy (self);
}


static void ___lambda13__gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	__lambda13_ (self);
}


Main* main_construct (GType object_type) {
	Main * self = NULL;
	gboolean _tmp0_;
	gboolean _tmp1_;
	gchar* _tmp2_;
	GtkMenuBar* _tmp3_;
	GtkMenuBar* _tmp4_;
	GtkMenuBar* menubar;
	GtkMenu* _tmp5_;
	GtkMenu* _tmp6_;
	GtkMenu* notesMenu;
	GtkMenuItem* _tmp7_;
	GtkMenuItem* _tmp8_;
	GtkMenuItem* menuNewNote;
	GtkMenuItem* _tmp9_;
	GtkMenuItem* _tmp10_;
	GtkMenuItem* menuChangeNotesDir;
	GtkMenuItem* _tmp11_;
	GtkMenuItem* _tmp12_;
	GtkMenuItem* menuOpenNotesLocation;
	GtkMenuItem* _tmp13_;
	GtkMenuItem* _tmp14_;
	GtkMenuItem* menuClose;
	GtkSeparatorMenuItem* _tmp15_;
	GtkSeparatorMenuItem* _tmp16_;
	GtkMenuItem* _tmp17_;
	GtkMenuItem* _tmp18_;
	GtkMenuItem* notesMenuItem;
	GtkMenu* _tmp19_;
	GtkMenu* _tmp20_;
	GtkMenu* settingsMenu;
	GtkMenuItem* _tmp21_;
	GtkMenuItem* _tmp22_;
	GtkMenuItem* menuIncreaseFontSize;
	GtkMenuItem* _tmp23_;
	GtkMenuItem* _tmp24_;
	GtkMenuItem* menuDecreaseFontSize;
	GtkMenuItem* _tmp25_;
	GtkMenuItem* _tmp26_;
	GtkMenuItem* settingsMenuItem;
	GtkMenu* _tmp27_;
	GtkMenu* _tmp28_;
	GtkMenu* helpMenu;
	GtkMenuItem* _tmp29_;
	GtkMenuItem* _tmp30_;
	GtkMenuItem* menuKeyboardShortcuts;
	GtkMenuItem* _tmp31_;
	GtkMenuItem* _tmp32_;
	GtkMenuItem* menuAbout;
	GtkMenuItem* _tmp33_;
	GtkMenuItem* _tmp34_;
	GtkMenuItem* helpMenuItem;
	GtkEntry* _tmp35_;
	GtkEntry* _tmp36_;
	GtkTreeView* _tmp37_;
	GtkTreeView* _tmp38_;
	GtkTextView* _tmp39_;
	GtkTextView* _tmp40_;
	GtkTextView* _tmp41_;
	GtkTextBuffer* _tmp42_;
	GtkTextBuffer* _tmp43_;
	GtkTextView* _tmp44_;
	GtkTextBuffer* _tmp45_;
	GtkTextBuffer* _tmp46_;
	NoteEditor* _tmp47_;
	GtkTextView* _tmp48_;
	GtkTextView* _tmp49_;
	GtkTextView* _tmp50_;
	GtkTextView* _tmp51_;
	GtkTextView* _tmp52_;
	GtkTextView* _tmp53_;
	GtkTextView* _tmp54_;
	GtkScrolledWindow* _tmp55_;
	GtkScrolledWindow* _tmp56_;
	GtkScrolledWindow* scroll1;
	GtkTreeView* _tmp57_;
	GtkBox* _tmp58_;
	GtkBox* _tmp59_;
	GtkBox* vbox;
	GtkScrolledWindow* _tmp60_;
	GtkScrolledWindow* _tmp61_;
	GtkScrolledWindow* scroll;
	GtkTextView* _tmp62_;
	GtkPaned* _tmp63_;
	GtkPaned* _tmp64_;
	GtkPaned* paned;
	GtkBox* _tmp65_;
	GtkBox* _tmp66_;
	GtkBox* vbox1;
	gint _tmp67_;
	self = (Main*) g_object_new (object_type, NULL);
	_tmp0_ = zystem_get_debugOn ();
	_tmp1_ = _tmp0_;
	zystem_set_debugOn (!MAIN_isInstalled);
	user_data_initializeUserData ();
	_tmp2_ = g_strdup ("");
	_g_free0 (self->priv->lastKeyName);
	self->priv->lastKeyName = _tmp2_;
	gtk_window_set_title ((GtkWindow*) self, "P.S. Notes.");
	g_object_set ((GtkWindow*) self, "window-position", GTK_WIN_POS_CENTER, NULL);
	gtk_window_set_default_size ((GtkWindow*) self, 530, 400);
	_tmp3_ = (GtkMenuBar*) gtk_menu_bar_new ();
	_tmp4_ = g_object_ref_sink (_tmp3_);
	menubar = _tmp4_;
	_tmp5_ = (GtkMenu*) gtk_menu_new ();
	_tmp6_ = g_object_ref_sink (_tmp5_);
	notesMenu = _tmp6_;
	_tmp7_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("New Note");
	_tmp8_ = g_object_ref_sink (_tmp7_);
	menuNewNote = _tmp8_;
	g_signal_connect_object (menuNewNote, "activate", (GCallback) ___lambda2__gtk_menu_item_activate, self, 0);
	_tmp9_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Change Notes Folder");
	_tmp10_ = g_object_ref_sink (_tmp9_);
	menuChangeNotesDir = _tmp10_;
	g_signal_connect_object (menuChangeNotesDir, "activate", (GCallback) ___lambda3__gtk_menu_item_activate, self, 0);
	_tmp11_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("View Notes Files");
	_tmp12_ = g_object_ref_sink (_tmp11_);
	menuOpenNotesLocation = _tmp12_;
	g_signal_connect_object (menuOpenNotesLocation, "activate", (GCallback) ___lambda4__gtk_menu_item_activate, self, 0);
	_tmp13_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Close P.S. Notes.");
	_tmp14_ = g_object_ref_sink (_tmp13_);
	menuClose = _tmp14_;
	g_signal_connect_object (menuClose, "activate", (GCallback) ___lambda5__gtk_menu_item_activate, self, 0);
	gtk_menu_shell_append ((GtkMenuShell*) notesMenu, (GtkWidget*) menuNewNote);
	gtk_menu_shell_append ((GtkMenuShell*) notesMenu, (GtkWidget*) menuChangeNotesDir);
	gtk_menu_shell_append ((GtkMenuShell*) notesMenu, (GtkWidget*) menuOpenNotesLocation);
	_tmp15_ = (GtkSeparatorMenuItem*) gtk_separator_menu_item_new ();
	_tmp16_ = g_object_ref_sink (_tmp15_);
	gtk_menu_shell_append ((GtkMenuShell*) notesMenu, (GtkWidget*) ((GtkMenuItem*) _tmp16_));
	_g_object_unref0 (_tmp16_);
	gtk_menu_shell_append ((GtkMenuShell*) notesMenu, (GtkWidget*) menuClose);
	_tmp17_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Notes");
	_tmp18_ = g_object_ref_sink (_tmp17_);
	notesMenuItem = _tmp18_;
	gtk_menu_item_set_submenu (notesMenuItem, (GtkWidget*) notesMenu);
	gtk_menu_shell_append ((GtkMenuShell*) menubar, (GtkWidget*) notesMenuItem);
	_tmp19_ = (GtkMenu*) gtk_menu_new ();
	_tmp20_ = g_object_ref_sink (_tmp19_);
	settingsMenu = _tmp20_;
	_tmp21_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Increase font size");
	_tmp22_ = g_object_ref_sink (_tmp21_);
	menuIncreaseFontSize = _tmp22_;
	g_signal_connect_object (menuIncreaseFontSize, "activate", (GCallback) ___lambda6__gtk_menu_item_activate, self, 0);
	_tmp23_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Decrease font size");
	_tmp24_ = g_object_ref_sink (_tmp23_);
	menuDecreaseFontSize = _tmp24_;
	g_signal_connect_object (menuDecreaseFontSize, "activate", (GCallback) ___lambda7__gtk_menu_item_activate, self, 0);
	gtk_menu_shell_append ((GtkMenuShell*) settingsMenu, (GtkWidget*) menuIncreaseFontSize);
	gtk_menu_shell_append ((GtkMenuShell*) settingsMenu, (GtkWidget*) menuDecreaseFontSize);
	_tmp25_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Settings");
	_tmp26_ = g_object_ref_sink (_tmp25_);
	settingsMenuItem = _tmp26_;
	gtk_menu_item_set_submenu (settingsMenuItem, (GtkWidget*) settingsMenu);
	gtk_menu_shell_append ((GtkMenuShell*) menubar, (GtkWidget*) settingsMenuItem);
	_tmp27_ = (GtkMenu*) gtk_menu_new ();
	_tmp28_ = g_object_ref_sink (_tmp27_);
	helpMenu = _tmp28_;
	_tmp29_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Keyboard Shortcuts");
	_tmp30_ = g_object_ref_sink (_tmp29_);
	menuKeyboardShortcuts = _tmp30_;
	g_signal_connect_object (menuKeyboardShortcuts, "activate", (GCallback) ___lambda8__gtk_menu_item_activate, self, 0);
	_tmp31_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("About P.S. Notes.");
	_tmp32_ = g_object_ref_sink (_tmp31_);
	menuAbout = _tmp32_;
	g_signal_connect_object (menuAbout, "activate", (GCallback) ___lambda9__gtk_menu_item_activate, self, 0);
	gtk_menu_shell_append ((GtkMenuShell*) helpMenu, (GtkWidget*) menuKeyboardShortcuts);
	gtk_menu_shell_append ((GtkMenuShell*) helpMenu, (GtkWidget*) menuAbout);
	_tmp33_ = (GtkMenuItem*) gtk_menu_item_new_with_label ("Help");
	_tmp34_ = g_object_ref_sink (_tmp33_);
	helpMenuItem = _tmp34_;
	gtk_menu_item_set_submenu (helpMenuItem, (GtkWidget*) helpMenu);
	gtk_menu_shell_append ((GtkMenuShell*) menubar, (GtkWidget*) helpMenuItem);
	_tmp35_ = (GtkEntry*) gtk_entry_new ();
	_tmp36_ = g_object_ref_sink (_tmp35_);
	_g_object_unref0 (self->priv->txtFilter);
	self->priv->txtFilter = _tmp36_;
	_tmp37_ = (GtkTreeView*) gtk_tree_view_new ();
	_tmp38_ = g_object_ref_sink (_tmp37_);
	_g_object_unref0 (self->priv->notesView);
	self->priv->notesView = _tmp38_;
	main_setupNotesView (self);
	_tmp39_ = (GtkTextView*) gtk_text_view_new ();
	_tmp40_ = g_object_ref_sink (_tmp39_);
	_g_object_unref0 (self->priv->noteTextView);
	self->priv->noteTextView = _tmp40_;
	_tmp41_ = self->priv->noteTextView;
	_tmp42_ = gtk_text_view_get_buffer (_tmp41_);
	_tmp43_ = _tmp42_;
	g_signal_connect_object (_tmp43_, "changed", (GCallback) ___lambda11__gtk_text_buffer_changed, self, 0);
	_tmp44_ = self->priv->noteTextView;
	_tmp45_ = gtk_text_view_get_buffer (_tmp44_);
	_tmp46_ = _tmp45_;
	_tmp47_ = note_editor_new (_tmp46_);
	_g_object_unref0 (self->priv->editor);
	self->priv->editor = _tmp47_;
	_tmp48_ = self->priv->noteTextView;
	gtk_text_view_set_pixels_above_lines (_tmp48_, 2);
	_tmp49_ = self->priv->noteTextView;
	gtk_text_view_set_pixels_below_lines (_tmp49_, 2);
	_tmp50_ = self->priv->noteTextView;
	gtk_text_view_set_pixels_inside_wrap (_tmp50_, 4);
	_tmp51_ = self->priv->noteTextView;
	gtk_text_view_set_wrap_mode (_tmp51_, GTK_WRAP_WORD_CHAR);
	_tmp52_ = self->priv->noteTextView;
	gtk_text_view_set_left_margin (_tmp52_, 4);
	_tmp53_ = self->priv->noteTextView;
	gtk_text_view_set_right_margin (_tmp53_, 4);
	_tmp54_ = self->priv->noteTextView;
	gtk_text_view_set_accepts_tab (_tmp54_, TRUE);
	_tmp55_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	_tmp56_ = g_object_ref_sink (_tmp55_);
	scroll1 = _tmp56_;
	gtk_scrolled_window_set_policy (scroll1, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
	gtk_scrolled_window_set_min_content_width (scroll1, 160);
	_tmp57_ = self->priv->notesView;
	gtk_container_add ((GtkContainer*) scroll1, (GtkWidget*) _tmp57_);
	g_object_set ((GtkWidget*) scroll1, "expand", TRUE, NULL);
	_tmp58_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 2);
	_tmp59_ = g_object_ref_sink (_tmp58_);
	vbox = _tmp59_;
	gtk_box_pack_start (vbox, (GtkWidget*) scroll1, TRUE, TRUE, (guint) 2);
	_tmp60_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	_tmp61_ = g_object_ref_sink (_tmp60_);
	scroll = _tmp61_;
	gtk_scrolled_window_set_shadow_type (scroll, GTK_SHADOW_ETCHED_OUT);
	gtk_scrolled_window_set_policy (scroll, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
	gtk_scrolled_window_set_min_content_width (scroll, 251);
	gtk_scrolled_window_set_min_content_height (scroll, 280);
	_tmp62_ = self->priv->noteTextView;
	gtk_container_add ((GtkContainer*) scroll, (GtkWidget*) _tmp62_);
	g_object_set ((GtkWidget*) scroll, "expand", TRUE, NULL);
	_tmp63_ = (GtkPaned*) gtk_paned_new (GTK_ORIENTATION_HORIZONTAL);
	_tmp64_ = g_object_ref_sink (_tmp63_);
	paned = _tmp64_;
	gtk_paned_add1 (paned, (GtkWidget*) vbox);
	gtk_paned_add2 (paned, (GtkWidget*) scroll);
	_tmp65_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	_tmp66_ = g_object_ref_sink (_tmp65_);
	vbox1 = _tmp66_;
	gtk_box_pack_start (vbox1, (GtkWidget*) menubar, FALSE, TRUE, (guint) 0);
	gtk_box_pack_start (vbox1, (GtkWidget*) paned, TRUE, TRUE, (guint) 2);
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) vbox1);
	self->priv->startingFontSize = 10;
	_tmp67_ = self->priv->startingFontSize;
	self->priv->fontSize = _tmp67_;
	main_resetFontSize (self);
	g_signal_connect_object ((GtkWidget*) self, "key-press-event", (GCallback) ___lambda12__gtk_widget_key_press_event, self, 0);
	g_signal_connect_object ((GtkWidget*) self, "destroy", (GCallback) ___lambda13__gtk_widget_destroy, self, 0);
	_g_object_unref0 (vbox1);
	_g_object_unref0 (paned);
	_g_object_unref0 (scroll);
	_g_object_unref0 (vbox);
	_g_object_unref0 (scroll1);
	_g_object_unref0 (helpMenuItem);
	_g_object_unref0 (menuAbout);
	_g_object_unref0 (menuKeyboardShortcuts);
	_g_object_unref0 (helpMenu);
	_g_object_unref0 (settingsMenuItem);
	_g_object_unref0 (menuDecreaseFontSize);
	_g_object_unref0 (menuIncreaseFontSize);
	_g_object_unref0 (settingsMenu);
	_g_object_unref0 (notesMenuItem);
	_g_object_unref0 (menuClose);
	_g_object_unref0 (menuOpenNotesLocation);
	_g_object_unref0 (menuChangeNotesDir);
	_g_object_unref0 (menuNewNote);
	_g_object_unref0 (notesMenu);
	_g_object_unref0 (menubar);
	return self;
}


Main* main_new (void) {
	return main_construct (TYPE_MAIN);
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (Block1Data* _data1_) {
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		_g_object_unref0 (_data1_->self);
		_g_object_unref0 (_data1_->treeSelection);
		g_slice_free (Block1Data, _data1_);
	}
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void __lambda10_ (Block1Data* _data1_) {
	Main * self;
	self = _data1_->self;
	main_noteSelected (self, _data1_->treeSelection);
}


static void ___lambda10__gtk_tree_selection_changed (GtkTreeSelection* _sender, gpointer self) {
	__lambda10_ (self);
}


static void main_setupNotesView (Main* self) {
	Block1Data* _data1_;
	GtkListStore* _tmp0_;
	GtkListStore* listmodel;
	GtkTreeView* _tmp1_;
	GtkTreeView* _tmp2_;
	GtkCellRendererText* _tmp3_;
	GtkCellRendererText* _tmp4_;
	GtkTreeView* _tmp5_;
	GtkTreeSelection* _tmp6_ = NULL;
	GtkTreeSelection* _tmp7_;
	g_return_if_fail (self != NULL);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_tmp0_ = gtk_list_store_new (1, G_TYPE_STRING);
	listmodel = _tmp0_;
	_tmp1_ = self->priv->notesView;
	gtk_tree_view_set_model (_tmp1_, (GtkTreeModel*) listmodel);
	_tmp2_ = self->priv->notesView;
	_tmp3_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	_tmp4_ = g_object_ref_sink (_tmp3_);
	gtk_tree_view_insert_column_with_attributes (_tmp2_, -1, "Notes", (GtkCellRenderer*) _tmp4_, "text", 0, NULL);
	_g_object_unref0 (_tmp4_);
	main_loadNotesList (self);
	_tmp5_ = self->priv->notesView;
	_tmp6_ = gtk_tree_view_get_selection (_tmp5_);
	_tmp7_ = _g_object_ref0 (_tmp6_);
	_data1_->treeSelection = _tmp7_;
	gtk_tree_selection_set_mode (_data1_->treeSelection, GTK_SELECTION_SINGLE);
	g_signal_connect_data (_data1_->treeSelection, "changed", (GCallback) ___lambda10__gtk_tree_selection_changed, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
	_g_object_unref0 (listmodel);
	block1_data_unref (_data1_);
	_data1_ = NULL;
}


static void _g_free0_ (gpointer var) {
	var = (g_free (var), NULL);
}


static void _g_list_free__g_free0_ (GList* self) {
	g_list_foreach (self, (GFunc) _g_free0_, NULL);
	g_list_free (self);
}


static void main_loadNotesList (Main* self) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	self->priv->loadingNotes = TRUE;
	{
		GtkTreeView* _tmp0_;
		GtkTreeModel* _tmp1_;
		GtkTreeModel* _tmp2_;
		GtkListStore* _tmp3_;
		GtkListStore* listmodel;
		GtkListStore* _tmp4_;
		GtkListStore* _tmp5_;
		GList* notesList;
		GtkTreeIter iter = {0};
		const gchar* _tmp6_;
		const gchar* _tmp7_;
		GFile* _tmp8_ = NULL;
		GFile* notesDir;
		GFile* _tmp9_;
		GFileEnumerator* _tmp10_ = NULL;
		GFileEnumerator* enumerator;
		GFileInfo* fileInfo = NULL;
		_tmp0_ = self->priv->notesView;
		_tmp1_ = gtk_tree_view_get_model (_tmp0_);
		_tmp2_ = _tmp1_;
		_tmp3_ = _g_object_ref0 (GTK_IS_LIST_STORE (_tmp2_) ? ((GtkListStore*) _tmp2_) : NULL);
		listmodel = _tmp3_;
		_tmp4_ = listmodel;
		gtk_list_store_clear (_tmp4_);
		_tmp5_ = listmodel;
		gtk_tree_sortable_set_sort_column_id ((GtkTreeSortable*) _tmp5_, 0, GTK_SORT_ASCENDING);
		notesList = NULL;
		_tmp6_ = user_data_get_notesDirPath ();
		_tmp7_ = _tmp6_;
		_tmp8_ = g_file_new_for_path (_tmp7_);
		notesDir = _tmp8_;
		_tmp9_ = notesDir;
		_tmp10_ = g_file_enumerate_children (_tmp9_, G_FILE_ATTRIBUTE_STANDARD_NAME, 0, NULL, &_inner_error_);
		enumerator = _tmp10_;
		if (_inner_error_ != NULL) {
			_g_object_unref0 (notesDir);
			__g_list_free__g_free0_0 (notesList);
			_g_object_unref0 (listmodel);
			goto __catch0_g_error;
		}
		while (TRUE) {
			GFileEnumerator* _tmp11_;
			GFileInfo* _tmp12_ = NULL;
			GFileInfo* _tmp13_;
			GFileInfo* _tmp14_;
			GFileInfo* _tmp15_;
			const gchar* _tmp16_ = NULL;
			gchar* _tmp17_;
			gchar* filename;
			GFileInfo* _tmp18_;
			gchar* _tmp19_ = NULL;
			gchar* _tmp20_;
			gboolean _tmp21_;
			_tmp11_ = enumerator;
			_tmp12_ = g_file_enumerator_next_file (_tmp11_, NULL, &_inner_error_);
			_tmp13_ = _tmp12_;
			if (_inner_error_ != NULL) {
				_g_object_unref0 (fileInfo);
				_g_object_unref0 (enumerator);
				_g_object_unref0 (notesDir);
				__g_list_free__g_free0_0 (notesList);
				_g_object_unref0 (listmodel);
				goto __catch0_g_error;
			}
			_g_object_unref0 (fileInfo);
			fileInfo = _tmp13_;
			_tmp14_ = fileInfo;
			if (!(_tmp14_ != NULL)) {
				break;
			}
			_tmp15_ = fileInfo;
			_tmp16_ = g_file_info_get_name (_tmp15_);
			_tmp17_ = g_strdup (_tmp16_);
			filename = _tmp17_;
			_tmp18_ = fileInfo;
			_tmp19_ = file_utility_getFileExtension (_tmp18_);
			_tmp20_ = _tmp19_;
			_tmp21_ = g_strcmp0 (_tmp20_, ".txt") == 0;
			_g_free0 (_tmp20_);
			if (_tmp21_) {
				GFileInfo* _tmp22_;
				gchar* _tmp23_ = NULL;
				gchar* _tmp24_;
				GtkListStore* _tmp25_;
				GtkTreeIter _tmp26_ = {0};
				GtkListStore* _tmp27_;
				GtkTreeIter _tmp28_;
				GFileInfo* _tmp29_;
				gchar* _tmp30_ = NULL;
				gchar* _tmp31_;
				_tmp22_ = fileInfo;
				_tmp23_ = file_utility_getFileNameWithoutExtension (_tmp22_);
				_tmp24_ = _tmp23_;
				zystem_debug (_tmp24_);
				_g_free0 (_tmp24_);
				_tmp25_ = listmodel;
				gtk_list_store_append (_tmp25_, &_tmp26_);
				iter = _tmp26_;
				_tmp27_ = listmodel;
				_tmp28_ = iter;
				_tmp29_ = fileInfo;
				_tmp30_ = file_utility_getFileNameWithoutExtension (_tmp29_);
				_tmp31_ = _tmp30_;
				gtk_list_store_set (_tmp27_, &_tmp28_, 0, _tmp31_, -1);
				_g_free0 (_tmp31_);
			}
			_g_free0 (filename);
		}
		_g_object_unref0 (fileInfo);
		_g_object_unref0 (enumerator);
		_g_object_unref0 (notesDir);
		__g_list_free__g_free0_0 (notesList);
		_g_object_unref0 (listmodel);
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* e = NULL;
		FILE* _tmp32_;
		GError* _tmp33_;
		const gchar* _tmp34_;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp32_ = stderr;
		_tmp33_ = e;
		_tmp34_ = _tmp33_->message;
		fprintf (_tmp32_, "Error loading notes list: %s\n", _tmp34_);
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	self->priv->loadingNotes = FALSE;
}


static void main_noteSelected (Main* self, GtkTreeSelection* treeSelection) {
	gboolean _tmp0_;
	gboolean _tmp3_;
	Note* _tmp4_;
	GtkTreeModel* model = NULL;
	GtkTreeIter iter = {0};
	GtkTreeSelection* _tmp5_;
	GtkTreeModel* _tmp6_ = NULL;
	GtkTreeIter _tmp7_ = {0};
	GtkTreeModel* _tmp8_;
	GValue value = {0};
	GtkTreeModel* _tmp9_;
	GtkTreeIter _tmp10_;
	GValue _tmp11_ = {0};
	const gchar* _tmp12_ = NULL;
	gchar* _tmp13_;
	gchar* _tmp14_;
	const gchar* _tmp15_ = NULL;
	gchar* _tmp16_;
	gchar* noteTitle;
	const gchar* _tmp17_;
	Note* _tmp18_;
	NoteEditor* _tmp19_;
	Note* _tmp20_;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (treeSelection != NULL);
	_tmp0_ = self->priv->firstLaunch;
	if (_tmp0_) {
		GtkTreeSelection* _tmp1_;
		GtkTextView* _tmp2_;
		_tmp1_ = treeSelection;
		gtk_tree_selection_unselect_all (_tmp1_);
		_tmp2_ = self->priv->noteTextView;
		g_object_set ((GtkWidget*) _tmp2_, "is-focus", TRUE, NULL);
		self->priv->firstLaunch = FALSE;
		return;
	}
	_tmp3_ = self->priv->loadingNotes;
	if (_tmp3_) {
		return;
	}
	_tmp4_ = self->priv->note;
	if (_tmp4_ != NULL) {
		main_seldomSave (self, NULL, NULL);
	}
	_tmp5_ = treeSelection;
	gtk_tree_selection_get_selected (_tmp5_, &_tmp6_, &_tmp7_);
	_g_object_unref0 (model);
	_tmp8_ = _g_object_ref0 (_tmp6_);
	model = _tmp8_;
	iter = _tmp7_;
	_tmp9_ = model;
	_tmp10_ = iter;
	gtk_tree_model_get_value (_tmp9_, &_tmp10_, 0, &_tmp11_);
	G_IS_VALUE (&value) ? (g_value_unset (&value), NULL) : NULL;
	value = _tmp11_;
	_tmp12_ = g_value_get_string (&value);
	_tmp13_ = g_strconcat ("SELECTION IS: ", _tmp12_, NULL);
	_tmp14_ = _tmp13_;
	zystem_debug (_tmp14_);
	_g_free0 (_tmp14_);
	_tmp15_ = g_value_get_string (&value);
	_tmp16_ = g_strdup (_tmp15_);
	noteTitle = _tmp16_;
	self->priv->isOpening = TRUE;
	_tmp17_ = noteTitle;
	_tmp18_ = note_new (_tmp17_);
	_g_object_unref0 (self->priv->note);
	self->priv->note = _tmp18_;
	_tmp19_ = self->priv->editor;
	_tmp20_ = self->priv->note;
	_tmp21_ = note_getContents (_tmp20_);
	_tmp22_ = _tmp21_;
	note_editor_startNewNote (_tmp19_, _tmp22_);
	_g_free0 (_tmp22_);
	self->priv->needsSave = FALSE;
	self->priv->isOpening = FALSE;
	_g_free0 (noteTitle);
	G_IS_VALUE (&value) ? (g_value_unset (&value), NULL) : NULL;
	_g_object_unref0 (model);
}


gboolean main_onKeyPress (Main* self, GdkEventKey* key) {
	gboolean result = FALSE;
	guint keyval = 0U;
	GdkEventKey _tmp0_;
	guint _tmp1_;
	GdkModifierType state = 0;
	GdkEventKey _tmp2_;
	GdkModifierType _tmp3_;
	GdkModifierType _tmp4_;
	gboolean ctrl;
	GdkModifierType _tmp5_;
	gboolean shift;
	guint _tmp6_;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_;
	gchar* keyName;
	gboolean _tmp9_ = FALSE;
	gboolean _tmp10_;
	gboolean _tmp12_;
	const gchar* _tmp47_;
	gchar* _tmp48_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (key != NULL, FALSE);
	_tmp0_ = *key;
	_tmp1_ = _tmp0_.keyval;
	keyval = _tmp1_;
	_tmp2_ = *key;
	_tmp3_ = _tmp2_.state;
	state = _tmp3_;
	_tmp4_ = state;
	ctrl = (_tmp4_ & GDK_CONTROL_MASK) != 0;
	_tmp5_ = state;
	shift = (_tmp5_ & GDK_SHIFT_MASK) != 0;
	_tmp6_ = keyval;
	_tmp7_ = gdk_keyval_name (_tmp6_);
	_tmp8_ = g_strdup (_tmp7_);
	keyName = _tmp8_;
	_tmp10_ = ctrl;
	if (_tmp10_) {
		gboolean _tmp11_;
		_tmp11_ = shift;
		_tmp9_ = _tmp11_;
	} else {
		_tmp9_ = FALSE;
	}
	_tmp12_ = _tmp9_;
	if (_tmp12_) {
		const gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* _tmp15_;
		const gchar* _tmp16_;
		const gchar* _tmp17_;
		GQuark _tmp19_ = 0U;
		static GQuark _tmp18_label0 = 0;
		_tmp13_ = keyName;
		_tmp14_ = g_strconcat ("Ctrl+Shift+", _tmp13_, NULL);
		_tmp15_ = _tmp14_;
		zystem_debug (_tmp15_);
		_g_free0 (_tmp15_);
		_tmp16_ = keyName;
		_tmp17_ = _tmp16_;
		_tmp19_ = (NULL == _tmp17_) ? 0 : g_quark_from_string (_tmp17_);
		if (_tmp19_ == ((0 != _tmp18_label0) ? _tmp18_label0 : (_tmp18_label0 = g_quark_from_static_string ("Z")))) {
			switch (0) {
				default:
				{
					zystem_debug ("Y'all hit Ctrl+Shift+Z");
					break;
				}
			}
		} else {
			switch (0) {
				default:
				{
					const gchar* _tmp20_;
					gchar* _tmp21_;
					gchar* _tmp22_;
					gchar* _tmp23_;
					gchar* _tmp24_;
					_tmp20_ = keyName;
					_tmp21_ = g_strconcat ("What should Ctrl+Shift+", _tmp20_, NULL);
					_tmp22_ = _tmp21_;
					_tmp23_ = g_strconcat (_tmp22_, " do?", NULL);
					_tmp24_ = _tmp23_;
					zystem_debug (_tmp24_);
					_g_free0 (_tmp24_);
					_g_free0 (_tmp22_);
					break;
				}
			}
		}
	} else {
		gboolean _tmp25_;
		_tmp25_ = ctrl;
		if (_tmp25_) {
			const gchar* _tmp26_;
			const gchar* _tmp27_;
			GQuark _tmp29_ = 0U;
			static GQuark _tmp28_label0 = 0;
			static GQuark _tmp28_label1 = 0;
			static GQuark _tmp28_label2 = 0;
			static GQuark _tmp28_label3 = 0;
			static GQuark _tmp28_label4 = 0;
			static GQuark _tmp28_label5 = 0;
			static GQuark _tmp28_label6 = 0;
			static GQuark _tmp28_label7 = 0;
			_tmp26_ = keyName;
			_tmp27_ = _tmp26_;
			_tmp29_ = (NULL == _tmp27_) ? 0 : g_quark_from_string (_tmp27_);
			if (_tmp29_ == ((0 != _tmp28_label0) ? _tmp28_label0 : (_tmp28_label0 = g_quark_from_static_string ("z")))) {
				switch (0) {
					default:
					{
						break;
					}
				}
			} else if (_tmp29_ == ((0 != _tmp28_label1) ? _tmp28_label1 : (_tmp28_label1 = g_quark_from_static_string ("y")))) {
				switch (0) {
					default:
					{
						break;
					}
				}
			} else if (_tmp29_ == ((0 != _tmp28_label2) ? _tmp28_label2 : (_tmp28_label2 = g_quark_from_static_string ("d")))) {
				switch (0) {
					default:
					{
						break;
					}
				}
			} else if (_tmp29_ == ((0 != _tmp28_label3) ? _tmp28_label3 : (_tmp28_label3 = g_quark_from_static_string ("n")))) {
				switch (0) {
					default:
					{
						main_createNewNote (self);
						break;
					}
				}
			} else if (_tmp29_ == ((0 != _tmp28_label4) ? _tmp28_label4 : (_tmp28_label4 = g_quark_from_static_string ("o")))) {
				switch (0) {
					default:
					{
						main_changeNotesDir (self);
						break;
					}
				}
			} else if (_tmp29_ == ((0 != _tmp28_label5) ? _tmp28_label5 : (_tmp28_label5 = g_quark_from_static_string ("equal")))) {
				switch (0) {
					default:
					{
						main_increaseFontSize (self);
						break;
					}
				}
			} else if (_tmp29_ == ((0 != _tmp28_label6) ? _tmp28_label6 : (_tmp28_label6 = g_quark_from_static_string ("minus")))) {
				switch (0) {
					default:
					{
						main_decreaseFontSize (self);
						break;
					}
				}
			} else if (_tmp29_ == ((0 != _tmp28_label7) ? _tmp28_label7 : (_tmp28_label7 = g_quark_from_static_string ("0")))) {
				switch (0) {
					default:
					{
						main_resetFontSize (self);
						break;
					}
				}
			} else {
				switch (0) {
					default:
					{
						const gchar* _tmp30_;
						gchar* _tmp31_;
						gchar* _tmp32_;
						gchar* _tmp33_;
						gchar* _tmp34_;
						_tmp30_ = keyName;
						_tmp31_ = g_strconcat ("What should Ctrl+", _tmp30_, NULL);
						_tmp32_ = _tmp31_;
						_tmp33_ = g_strconcat (_tmp32_, " do?", NULL);
						_tmp34_ = _tmp33_;
						zystem_debug (_tmp34_);
						_g_free0 (_tmp34_);
						_g_free0 (_tmp32_);
						break;
					}
				}
			}
		} else {
			gboolean _tmp35_ = FALSE;
			gboolean _tmp36_ = FALSE;
			gboolean _tmp37_;
			gboolean _tmp39_;
			gboolean _tmp42_;
			_tmp37_ = ctrl;
			if (_tmp37_) {
				_tmp36_ = TRUE;
			} else {
				gboolean _tmp38_;
				_tmp38_ = shift;
				_tmp36_ = _tmp38_;
			}
			_tmp39_ = _tmp36_;
			if (_tmp39_) {
				_tmp35_ = TRUE;
			} else {
				const gchar* _tmp40_;
				const gchar* _tmp41_;
				_tmp40_ = keyName;
				_tmp41_ = self->priv->lastKeyName;
				_tmp35_ = g_strcmp0 (_tmp40_, _tmp41_) == 0;
			}
			_tmp42_ = _tmp35_;
			if (!_tmp42_) {
				const gchar* _tmp43_;
				const gchar* _tmp44_;
				GQuark _tmp46_ = 0U;
				static GQuark _tmp45_label0 = 0;
				static GQuark _tmp45_label1 = 0;
				static GQuark _tmp45_label2 = 0;
				_tmp43_ = keyName;
				_tmp44_ = _tmp43_;
				_tmp46_ = (NULL == _tmp44_) ? 0 : g_quark_from_string (_tmp44_);
				if (((_tmp46_ == ((0 != _tmp45_label0) ? _tmp45_label0 : (_tmp45_label0 = g_quark_from_static_string ("period")))) || (_tmp46_ == ((0 != _tmp45_label1) ? _tmp45_label1 : (_tmp45_label1 = g_quark_from_static_string ("Return"))))) || (_tmp46_ == ((0 != _tmp45_label2) ? _tmp45_label2 : (_tmp45_label2 = g_quark_from_static_string ("space"))))) {
					switch (0) {
						default:
						{
							main_seldomSave (self, NULL, NULL);
							break;
						}
					}
				} else {
					switch (0) {
						default:
						{
							break;
						}
					}
				}
			}
		}
	}
	_tmp47_ = keyName;
	_tmp48_ = g_strdup (_tmp47_);
	_g_free0 (self->priv->lastKeyName);
	self->priv->lastKeyName = _tmp48_;
	result = FALSE;
	_g_free0 (keyName);
	return result;
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _tmp0_ = NULL;
	gchar* _result_;
	const gchar* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


void main_onTextChanged (Main* self, GtkTextBuffer* buffer) {
	gboolean _tmp0_;
	gboolean _tmp1_ = FALSE;
	Note* _tmp2_;
	gboolean _tmp6_;
	NoteEditor* _tmp18_;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_;
	gchar* _tmp21_ = NULL;
	gchar* _tmp22_;
	gchar* _tmp23_;
	gchar* _tmp24_;
	gboolean _tmp25_ = FALSE;
	gboolean _tmp26_ = FALSE;
	NoteEditor* _tmp27_;
	gint _tmp28_ = 0;
	gboolean _tmp34_;
	gboolean _tmp36_;
	NoteEditor* _tmp46_;
	gchar* _tmp47_ = NULL;
	gchar* _tmp48_;
	gchar* _tmp49_ = NULL;
	gchar* _tmp50_;
	gboolean _tmp51_;
	gboolean _tmp52_ = FALSE;
	NoteEditor* _tmp53_;
	gint _tmp54_ = 0;
	gboolean _tmp60_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (buffer != NULL);
	_tmp0_ = self->priv->isOpening;
	if (!_tmp0_) {
		self->priv->needsSave = TRUE;
	} else {
		return;
	}
	_tmp2_ = self->priv->note;
	if (_tmp2_ == NULL) {
		NoteEditor* _tmp3_;
		gchar* _tmp4_ = NULL;
		gchar* _tmp5_;
		_tmp3_ = self->priv->editor;
		_tmp4_ = note_editor_getText (_tmp3_);
		_tmp5_ = _tmp4_;
		_tmp1_ = g_strcmp0 (_tmp5_, "") != 0;
		_g_free0 (_tmp5_);
	} else {
		_tmp1_ = FALSE;
	}
	_tmp6_ = _tmp1_;
	if (_tmp6_) {
		NoteEditor* _tmp7_;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_;
		gchar* _tmp10_;
		gchar* _tmp11_;
		NoteEditor* _tmp12_;
		gchar* _tmp13_ = NULL;
		gchar* _tmp14_;
		gchar* _tmp15_ = NULL;
		gchar* _tmp16_;
		Note* _tmp17_;
		zystem_debug ("NOTE IS NULL, thank you very much!");
		_tmp7_ = self->priv->editor;
		_tmp8_ = note_editor_firstLine (_tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = g_strconcat ("Note title should be: ", _tmp9_, NULL);
		_tmp11_ = _tmp10_;
		zystem_debug (_tmp11_);
		_g_free0 (_tmp11_);
		_g_free0 (_tmp9_);
		_tmp12_ = self->priv->editor;
		_tmp13_ = note_editor_firstLine (_tmp12_);
		_tmp14_ = _tmp13_;
		_tmp15_ = string_strip (_tmp14_);
		_tmp16_ = _tmp15_;
		_tmp17_ = note_new (_tmp16_);
		_g_object_unref0 (self->priv->note);
		self->priv->note = _tmp17_;
		_g_free0 (_tmp16_);
		_g_free0 (_tmp14_);
		main_loadNotesList (self);
	}
	_tmp18_ = self->priv->editor;
	_tmp19_ = note_editor_firstLine (_tmp18_);
	_tmp20_ = _tmp19_;
	_tmp21_ = string_strip (_tmp20_);
	_tmp22_ = _tmp21_;
	_tmp23_ = g_strconcat ("PAY ATTENTIONS TO MEEEEEEEEEEEEEE ", _tmp22_, NULL);
	_tmp24_ = _tmp23_;
	zystem_debug (_tmp24_);
	_g_free0 (_tmp24_);
	_g_free0 (_tmp22_);
	_g_free0 (_tmp20_);
	_tmp27_ = self->priv->editor;
	_tmp28_ = note_editor_lineCount (_tmp27_);
	if (_tmp28_ > 0) {
		NoteEditor* _tmp29_;
		gchar* _tmp30_ = NULL;
		gchar* _tmp31_;
		gchar* _tmp32_ = NULL;
		gchar* _tmp33_;
		_tmp29_ = self->priv->editor;
		_tmp30_ = note_editor_firstLine (_tmp29_);
		_tmp31_ = _tmp30_;
		_tmp32_ = string_strip (_tmp31_);
		_tmp33_ = _tmp32_;
		_tmp26_ = g_strcmp0 (_tmp33_, "") != 0;
		_g_free0 (_tmp33_);
		_g_free0 (_tmp31_);
	} else {
		_tmp26_ = FALSE;
	}
	_tmp34_ = _tmp26_;
	if (_tmp34_) {
		gboolean _tmp35_ = FALSE;
		_tmp35_ = main_noteTitleChanged (self);
		_tmp25_ = _tmp35_;
	} else {
		_tmp25_ = FALSE;
	}
	_tmp36_ = _tmp25_;
	if (_tmp36_) {
		Note* _tmp37_;
		NoteEditor* _tmp38_;
		gchar* _tmp39_ = NULL;
		gchar* _tmp40_;
		gchar* _tmp41_ = NULL;
		gchar* _tmp42_;
		NoteEditor* _tmp43_;
		gchar* _tmp44_ = NULL;
		gchar* _tmp45_;
		zystem_debug ("Oh boy, the note title changed. Let's rename that sucker.");
		_tmp37_ = self->priv->note;
		_tmp38_ = self->priv->editor;
		_tmp39_ = note_editor_firstLine (_tmp38_);
		_tmp40_ = _tmp39_;
		_tmp41_ = string_strip (_tmp40_);
		_tmp42_ = _tmp41_;
		_tmp43_ = self->priv->editor;
		_tmp44_ = note_editor_getText (_tmp43_);
		_tmp45_ = _tmp44_;
		note_rename (_tmp37_, _tmp42_, _tmp45_);
		_g_free0 (_tmp45_);
		_g_free0 (_tmp42_);
		_g_free0 (_tmp40_);
		main_loadNotesList (self);
	}
	_tmp46_ = self->priv->editor;
	_tmp47_ = note_editor_firstLine (_tmp46_);
	_tmp48_ = _tmp47_;
	_tmp49_ = string_strip (_tmp48_);
	_tmp50_ = _tmp49_;
	_tmp51_ = g_strcmp0 (_tmp50_, "") == 0;
	_g_free0 (_tmp50_);
	_g_free0 (_tmp48_);
	if (_tmp51_) {
		main_seldomSave (self, NULL, NULL);
	}
	_tmp53_ = self->priv->editor;
	_tmp54_ = note_editor_lineCount (_tmp53_);
	if (_tmp54_ == 0) {
		_tmp52_ = TRUE;
	} else {
		NoteEditor* _tmp55_;
		gchar* _tmp56_ = NULL;
		gchar* _tmp57_;
		gchar* _tmp58_ = NULL;
		gchar* _tmp59_;
		_tmp55_ = self->priv->editor;
		_tmp56_ = note_editor_firstLine (_tmp55_);
		_tmp57_ = _tmp56_;
		_tmp58_ = string_strip (_tmp57_);
		_tmp59_ = _tmp58_;
		_tmp52_ = g_strcmp0 (_tmp59_, "") == 0;
		_g_free0 (_tmp59_);
		_g_free0 (_tmp57_);
	}
	_tmp60_ = _tmp52_;
	if (_tmp60_) {
		main_loadNotesList (self);
	}
}


static gboolean main_noteTitleChanged (Main* self) {
	gboolean result = FALSE;
	NoteEditor* _tmp0_;
	gint _tmp1_ = 0;
	NoteEditor* _tmp2_;
	gchar* _tmp3_ = NULL;
	gchar* _tmp4_;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_;
	Note* _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	gboolean _tmp10_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->editor;
	_tmp1_ = note_editor_lineCount (_tmp0_);
	if (_tmp1_ == 0) {
		result = FALSE;
		return result;
	}
	_tmp2_ = self->priv->editor;
	_tmp3_ = note_editor_firstLine (_tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = string_strip (_tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = self->priv->note;
	_tmp8_ = note_get_title (_tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = g_strcmp0 (_tmp6_, _tmp9_) != 0;
	_g_free0 (_tmp6_);
	_g_free0 (_tmp4_);
	result = _tmp10_;
	return result;
}


static void main_createNewNote (Main* self) {
	Note* _tmp0_;
	NoteEditor* _tmp1_;
	Note* _tmp2_;
	const gchar* _tmp3_;
	const gchar* _tmp4_;
	GtkTextView* _tmp5_;
	g_return_if_fail (self != NULL);
	_tmp0_ = note_new ("NEW NOTE");
	_g_object_unref0 (self->priv->note);
	self->priv->note = _tmp0_;
	main_loadNotesList (self);
	self->priv->needsSave = TRUE;
	_tmp1_ = self->priv->editor;
	_tmp2_ = self->priv->note;
	_tmp3_ = note_get_title (_tmp2_);
	_tmp4_ = _tmp3_;
	note_editor_startNewNote (_tmp1_, _tmp4_);
	_tmp5_ = self->priv->noteTextView;
	g_signal_emit_by_name (_tmp5_, "select-all", TRUE);
}


/**
 * Font size methods
 */
static void main_resetFontSize (Main* self) {
	gint _tmp0_;
	gint _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->startingFontSize;
	_tmp1_ = self->priv->fontSize;
	main_changeFontSize (self, _tmp0_ - _tmp1_);
}


static void main_increaseFontSize (Main* self) {
	g_return_if_fail (self != NULL);
	main_changeFontSize (self, 1);
}


static void main_decreaseFontSize (Main* self) {
	g_return_if_fail (self != NULL);
	main_changeFontSize (self, -1);
}


static gpointer _pango_font_description_copy0 (gpointer self) {
	return self ? pango_font_description_copy (self) : NULL;
}


static void main_changeFontSize (Main* self, gint byThisMuch) {
	gboolean _tmp0_ = FALSE;
	gint _tmp1_;
	gint _tmp2_;
	gboolean _tmp5_;
	gint _tmp11_;
	gint _tmp12_;
	gint _tmp13_;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_;
	gchar* _tmp16_;
	gchar* _tmp17_;
	GtkTextView* _tmp18_;
	GtkStyle* _tmp19_;
	GtkStyle* _tmp20_;
	GtkStyleContext* _tmp21_ = NULL;
	GtkStyleContext* _tmp22_;
	GtkStyleContext* _tmp23_;
	const PangoFontDescription* _tmp24_ = NULL;
	PangoFontDescription* _tmp25_;
	PangoFontDescription* _tmp26_;
	PangoFontDescription* font;
	gint _tmp27_;
	gdouble newFontSize;
	const PangoFontDescription* _tmp28_;
	gdouble _tmp29_;
	GtkTextView* _tmp30_;
	const PangoFontDescription* _tmp31_;
	g_return_if_fail (self != NULL);
	_tmp1_ = self->priv->fontSize;
	_tmp2_ = byThisMuch;
	if ((_tmp1_ + _tmp2_) < 6) {
		_tmp0_ = TRUE;
	} else {
		gint _tmp3_;
		gint _tmp4_;
		_tmp3_ = self->priv->fontSize;
		_tmp4_ = byThisMuch;
		_tmp0_ = (_tmp3_ + _tmp4_) > 50;
	}
	_tmp5_ = _tmp0_;
	if (_tmp5_) {
		gint _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		gchar* _tmp9_;
		gchar* _tmp10_;
		_tmp6_ = self->priv->fontSize;
		_tmp7_ = g_strdup_printf ("%i", _tmp6_);
		_tmp8_ = _tmp7_;
		_tmp9_ = g_strconcat ("Not changing font size, because it would be: ", _tmp8_, NULL);
		_tmp10_ = _tmp9_;
		zystem_debug (_tmp10_);
		_g_free0 (_tmp10_);
		_g_free0 (_tmp8_);
		return;
	}
	_tmp11_ = self->priv->fontSize;
	_tmp12_ = byThisMuch;
	self->priv->fontSize = _tmp11_ + _tmp12_;
	_tmp13_ = self->priv->fontSize;
	_tmp14_ = g_strdup_printf ("%i", _tmp13_);
	_tmp15_ = _tmp14_;
	_tmp16_ = g_strconcat ("Changing font size to: ", _tmp15_, NULL);
	_tmp17_ = _tmp16_;
	zystem_debug (_tmp17_);
	_g_free0 (_tmp17_);
	_g_free0 (_tmp15_);
	_tmp18_ = self->priv->noteTextView;
	_tmp19_ = gtk_widget_get_style ((GtkWidget*) _tmp18_);
	_tmp20_ = _tmp19_;
	g_object_get (_tmp20_, "context", &_tmp21_, NULL);
	_tmp22_ = _tmp21_;
	_tmp23_ = _tmp22_;
	_tmp24_ = gtk_style_context_get_font (_tmp23_, GTK_STATE_FLAG_NORMAL);
	_tmp25_ = _pango_font_description_copy0 (_tmp24_);
	_tmp26_ = _tmp25_;
	_g_object_unref0 (_tmp23_);
	font = _tmp26_;
	_tmp27_ = self->priv->fontSize;
	newFontSize = (gdouble) (_tmp27_ * PANGO_SCALE);
	_tmp28_ = font;
	_tmp29_ = newFontSize;
	pango_font_description_set_size (_tmp28_, (gint) _tmp29_);
	_tmp30_ = self->priv->noteTextView;
	_tmp31_ = font;
	gtk_widget_modify_font ((GtkWidget*) _tmp30_, _tmp31_);
	_pango_font_description_free0 (font);
}


static void main_seldomSave_data_free (gpointer _data) {
	main_seldomSaveData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (main_seldomSaveData, _data_);
}


static void main_seldomSave (Main* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	main_seldomSaveData* _data_;
	Main* _tmp0_;
	_data_ = g_slice_new0 (main_seldomSaveData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, main_seldomSave);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, main_seldomSave_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	main_seldomSave_co (_data_);
}


static void main_seldomSave_finish (Main* self, GAsyncResult* _res_) {
	main_seldomSaveData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static gchar* bool_to_string (gboolean self) {
	gchar* result = NULL;
	if (self) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup ("true");
		result = _tmp0_;
		return result;
	} else {
		gchar* _tmp1_;
		_tmp1_ = g_strdup ("false");
		result = _tmp1_;
		return result;
	}
}


static gboolean main_seldomSave_co (main_seldomSaveData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->priv->needsSave;
	_data_->_tmp1_ = NULL;
	_data_->_tmp1_ = bool_to_string (_data_->_tmp0_);
	_data_->_tmp2_ = _data_->_tmp1_;
	_data_->_tmp3_ = g_strconcat ("THIS IS A SELDOM SAVE POINT AND needsSave is ", _data_->_tmp2_, NULL);
	_data_->_tmp4_ = _data_->_tmp3_;
	zystem_debug (_data_->_tmp4_);
	_g_free0 (_data_->_tmp4_);
	_g_free0 (_data_->_tmp2_);
	_data_->_tmp6_ = user_data_get_seldomSave ();
	_data_->_tmp7_ = _data_->_tmp6_;
	if (_data_->_tmp7_) {
		_data_->_tmp8_ = _data_->self->priv->needsSave;
		_data_->_tmp5_ = _data_->_tmp8_;
	} else {
		_data_->_tmp5_ = FALSE;
	}
	_data_->_tmp9_ = _data_->_tmp5_;
	if (_data_->_tmp9_) {
		main_callSave (_data_->self, NULL, NULL);
	}
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void main_callSave_data_free (gpointer _data) {
	main_callSaveData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (main_callSaveData, _data_);
}


static void main_callSave (Main* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	main_callSaveData* _data_;
	Main* _tmp0_;
	_data_ = g_slice_new0 (main_callSaveData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, main_callSave);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, main_callSave_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	main_callSave_co (_data_);
}


static void main_callSave_finish (Main* self, GAsyncResult* _res_) {
	main_callSaveData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static gboolean main_callSave_co (main_callSaveData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	{
		_data_->_tmp0_ = _data_->self->priv->note;
		_data_->_tmp1_ = _data_->self->priv->editor;
		_data_->_tmp2_ = NULL;
		_data_->_tmp2_ = note_editor_getText (_data_->_tmp1_);
		_data_->_tmp3_ = _data_->_tmp2_;
		note_save (_data_->_tmp0_, _data_->_tmp3_, &_data_->_inner_error_);
		_g_free0 (_data_->_tmp3_);
		if (_data_->_inner_error_ != NULL) {
			goto __catch1_g_error;
		}
		_data_->self->priv->needsSave = FALSE;
	}
	goto __finally1;
	__catch1_g_error:
	{
		_data_->e = _data_->_inner_error_;
		_data_->_inner_error_ = NULL;
		zystem_debug ("There was an error saving the file.");
		_g_error_free0 (_data_->e);
	}
	__finally1:
	if (_data_->_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
		g_clear_error (&_data_->_inner_error_);
		return FALSE;
	}
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


void main_changeNotesDir (Main* self) {
	GtkFileChooserDialog* _tmp0_;
	GtkFileChooserDialog* _tmp1_;
	GtkFileChooserDialog* fileChooser;
	GtkFileChooserDialog* _tmp2_;
	gint _tmp3_ = 0;
	GtkFileChooserDialog* _tmp7_;
	g_return_if_fail (self != NULL);
	zystem_debug ("Changing Notes dir eh?");
	_tmp0_ = (GtkFileChooserDialog*) gtk_file_chooser_dialog_new ("Choose Notes Folder", (GtkWindow*) self, GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER, GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL, GTK_STOCK_OPEN, GTK_RESPONSE_ACCEPT, NULL);
	_tmp1_ = g_object_ref_sink (_tmp0_);
	fileChooser = _tmp1_;
	_tmp2_ = fileChooser;
	_tmp3_ = gtk_dialog_run ((GtkDialog*) _tmp2_);
	if (_tmp3_ == ((gint) GTK_RESPONSE_ACCEPT)) {
		GtkFileChooserDialog* _tmp4_;
		gchar* _tmp5_ = NULL;
		gchar* dirPath;
		const gchar* _tmp6_;
		_tmp4_ = fileChooser;
		_tmp5_ = gtk_file_chooser_get_filename ((GtkFileChooser*) _tmp4_);
		dirPath = _tmp5_;
		_tmp6_ = dirPath;
		user_data_setNotesDir (_tmp6_);
		main_loadNotesList (self);
		_g_free0 (dirPath);
	}
	_tmp7_ = fileChooser;
	gtk_widget_destroy ((GtkWidget*) _tmp7_);
	_g_object_unref0 (fileChooser);
}


static void main_openNotesLocation (Main* self) {
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = user_data_get_notesDirPath ();
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strconcat ("file://", _tmp1_, NULL);
	_tmp3_ = _tmp2_;
	gtk_show_uri (NULL, _tmp3_, (guint32) GDK_CURRENT_TIME, &_inner_error_);
	_g_free0 (_tmp3_);
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void main_showKeyboardShortcuts (Main* self) {
	GtkMessageDialog* _tmp0_;
	GtkMessageDialog* _tmp1_;
	GtkMessageDialog* dialog;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkMessageDialog*) gtk_message_dialog_new (NULL, GTK_DIALOG_MODAL, GTK_MESSAGE_INFO, GTK_BUTTONS_OK, MAIN_shortcutsText);
	_tmp1_ = g_object_ref_sink (_tmp0_);
	dialog = _tmp1_;
	gtk_window_set_title ((GtkWindow*) dialog, "Message Dialog");
	gtk_dialog_run ((GtkDialog*) dialog);
	gtk_widget_destroy ((GtkWidget*) dialog);
	_g_object_unref0 (dialog);
}


static void main_menuAboutClicked (Main* self) {
	GtkAboutDialog* _tmp0_;
	GtkAboutDialog* _tmp1_;
	GtkAboutDialog* about;
	g_return_if_fail (self != NULL);
	_tmp0_ = (GtkAboutDialog*) gtk_about_dialog_new ();
	_tmp1_ = g_object_ref_sink (_tmp0_);
	about = _tmp1_;
	gtk_about_dialog_set_program_name (about, "P.S. Notes.");
	gtk_about_dialog_set_comments (about, "Notes, plain and simple.");
	gtk_about_dialog_set_website (about, "http://zburnham.co.cc/");
	gtk_about_dialog_set_logo_icon_name (about, "psnotes");
	gtk_about_dialog_set_copyright (about, "by Zach Burnham");
	gtk_dialog_run ((GtkDialog*) about);
	gtk_widget_hide ((GtkWidget*) about);
	_g_object_unref0 (about);
}


/**
 * Quit DayNotes.
 */
void main_on_destroy (Main* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_;
	gboolean _tmp2_;
	gboolean _tmp4_;
	g_return_if_fail (self != NULL);
	_tmp1_ = user_data_get_seldomSave ();
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		gboolean _tmp3_;
		_tmp3_ = self->priv->needsSave;
		_tmp0_ = _tmp3_;
	} else {
		_tmp0_ = FALSE;
	}
	_tmp4_ = _tmp0_;
	if (_tmp4_) {
		zystem_debug ("Saving file on exit.");
		main_callSave (self, NULL, NULL);
	}
	gtk_main_quit ();
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	gtk_main_quit ();
}


gint main_main (gchar** args, int args_length1) {
	gint result = 0;
	Main* _tmp0_;
	Main* _tmp1_;
	Main* window;
	gtk_init (&args_length1, &args);
	_tmp0_ = main_new ();
	_tmp1_ = g_object_ref_sink (_tmp0_);
	window = _tmp1_;
	g_signal_connect ((GtkWidget*) window, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
	gtk_widget_show_all ((GtkWidget*) window);
	gtk_main ();
	result = 0;
	_g_object_unref0 (window);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return main_main (argv, argc);
}


static void main_class_init (MainClass * klass) {
	main_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (MainPrivate));
	G_OBJECT_CLASS (klass)->finalize = main_finalize;
}


static void main_instance_init (Main * self) {
	self->priv = MAIN_GET_PRIVATE (self);
	self->priv->needsSave = FALSE;
	self->priv->isOpening = FALSE;
	self->priv->loadingNotes = FALSE;
	self->priv->firstLaunch = TRUE;
}


static void main_finalize (GObject* obj) {
	Main * self;
	self = MAIN (obj);
	_g_object_unref0 (self->priv->note);
	_g_free0 (self->priv->lastKeyName);
	_g_object_unref0 (self->priv->txtFilter);
	_g_object_unref0 (self->priv->notesView);
	_g_object_unref0 (self->priv->noteTextView);
	_g_object_unref0 (self->priv->editor);
	G_OBJECT_CLASS (main_parent_class)->finalize (obj);
}


GType main_get_type (void) {
	static volatile gsize main_type_id__volatile = 0;
	if (g_once_init_enter (&main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (MainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Main), 0, (GInstanceInitFunc) main_instance_init, NULL };
		GType main_type_id;
		main_type_id = g_type_register_static (GTK_TYPE_WINDOW, "Main", &g_define_type_info, 0);
		g_once_init_leave (&main_type_id__volatile, main_type_id);
	}
	return main_type_id__volatile;
}



