/* Zystem.c generated by valac 0.14.2, the Vala compiler
 * generated from Zystem.vala, do not modify */

/* -*- Mode: vala; tab-width: 4; intend-tabs-mode: t -*- */
/* PSNotes
 *
 * Copyright (C) Zach Burnham 2012 <thejambi@gmail.com>
 *
PSNotes is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * PSNotes is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/*using GLib;*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <gio/gio.h>


#define TYPE_ZYSTEM (zystem_get_type ())
#define ZYSTEM(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_ZYSTEM, Zystem))
#define ZYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_ZYSTEM, ZystemClass))
#define IS_ZYSTEM(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_ZYSTEM))
#define IS_ZYSTEM_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_ZYSTEM))
#define ZYSTEM_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_ZYSTEM, ZystemClass))

typedef struct _Zystem Zystem;
typedef struct _ZystemClass ZystemClass;
typedef struct _ZystemPrivate ZystemPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _Zystem {
	GObject parent_instance;
	ZystemPrivate * priv;
};

struct _ZystemClass {
	GObjectClass parent_class;
};


static gpointer zystem_parent_class = NULL;
static gboolean zystem__debugOn;
static gboolean zystem__debugOn = FALSE;

GType zystem_get_type (void) G_GNUC_CONST;
enum  {
	ZYSTEM_DUMMY_PROPERTY
};
void zystem_println (const gchar* s);
void zystem_debug (const gchar* s);
gboolean zystem_get_debugOn (void);
void zystem_debugFileInfo (GFileInfo* file);
const gchar* g_file_type_to_string (GFileType self);
Zystem* zystem_new (void);
Zystem* zystem_construct (GType object_type);
void zystem_set_debugOn (gboolean value);
static void zystem_finalize (GObject* obj);
static void _vala_zystem_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_zystem_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


/**
 * My own println method. Hey, I'm a Java programmer!
 */
void zystem_println (const gchar* s) {
	FILE* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	g_return_if_fail (s != NULL);
	_tmp0_ = stdout;
	_tmp1_ = s;
	_tmp2_ = g_strconcat (_tmp1_, "\n", NULL);
	_tmp3_ = _tmp2_;
	fprintf (_tmp0_, "%s", _tmp3_);
	_g_free0 (_tmp3_);
}


/**
 * Debug method. Only prints if debug is set on.
 */
void zystem_debug (const gchar* s) {
	gboolean _tmp0_;
	gboolean _tmp1_;
	g_return_if_fail (s != NULL);
	_tmp0_ = zystem_get_debugOn ();
	_tmp1_ = _tmp0_;
	if (_tmp1_) {
		FILE* _tmp2_;
		const gchar* _tmp3_;
		gchar* _tmp4_;
		gchar* _tmp5_;
		_tmp2_ = stdout;
		_tmp3_ = s;
		_tmp4_ = g_strconcat (_tmp3_, "\n", NULL);
		_tmp5_ = _tmp4_;
		fprintf (_tmp2_, "%s", _tmp5_);
		_g_free0 (_tmp5_);
	}
}


/**
 * 
 */
void zystem_debugFileInfo (GFileInfo* file) {
	GFileInfo* _tmp0_;
	GFileType _tmp1_ = 0;
	GEnumValue* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	g_return_if_fail (file != NULL);
	_tmp0_ = file;
	_tmp1_ = g_file_info_get_file_type (_tmp0_);
	_tmp2_ = g_enum_get_value (g_type_class_ref (G_TYPE_FILE_TYPE), _tmp1_);
	_tmp3_ = g_strconcat ("File type: ", (_tmp2_ != NULL) ? _tmp2_->value_name : NULL, NULL);
	_tmp4_ = _tmp3_;
	zystem_debug (_tmp4_);
	_g_free0 (_tmp4_);
}


Zystem* zystem_construct (GType object_type) {
	Zystem * self = NULL;
	self = (Zystem*) g_object_new (object_type, NULL);
	return self;
}


Zystem* zystem_new (void) {
	return zystem_construct (TYPE_ZYSTEM);
}


gboolean zystem_get_debugOn (void) {
	gboolean result;
	gboolean _tmp0_;
	_tmp0_ = zystem__debugOn;
	result = _tmp0_;
	return result;
}


void zystem_set_debugOn (gboolean value) {
	gboolean _tmp0_;
	_tmp0_ = value;
	zystem__debugOn = _tmp0_;
}


static void zystem_class_init (ZystemClass * klass) {
	zystem_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->get_property = _vala_zystem_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_zystem_set_property;
	G_OBJECT_CLASS (klass)->finalize = zystem_finalize;
}


static void zystem_instance_init (Zystem * self) {
}


static void zystem_finalize (GObject* obj) {
	Zystem * self;
	self = ZYSTEM (obj);
	G_OBJECT_CLASS (zystem_parent_class)->finalize (obj);
}


/**
 * This class is for random helpful methods.
 */
GType zystem_get_type (void) {
	static volatile gsize zystem_type_id__volatile = 0;
	if (g_once_init_enter (&zystem_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ZystemClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) zystem_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Zystem), 0, (GInstanceInitFunc) zystem_instance_init, NULL };
		GType zystem_type_id;
		zystem_type_id = g_type_register_static (G_TYPE_OBJECT, "Zystem", &g_define_type_info, 0);
		g_once_init_leave (&zystem_type_id__volatile, zystem_type_id);
	}
	return zystem_type_id__volatile;
}


static void _vala_zystem_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	Zystem * self;
	self = ZYSTEM (object);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_zystem_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	Zystem * self;
	self = ZYSTEM (object);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



